# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e76ffda027cf469ec2b57d3fa9ef9532c1d53d34b97d0ee5dcbfd01d9b1bcec39346427f2b4b193ab565e53ade9d2aad5aa6eeb016afab380b2f59c160de355

test:
  secret_key_base: e3e7d4c1955c427117d14d285f044eb2e5fc56a49f2bfde5f313e947de199d45974609eab0d38eefdbe23c4efe33edac0a65b0fe30fcb65d6bd0e3e53817ceb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
